"""empty message

Revision ID: 32ea1969053c
Revises: e45d50667cd9
Create Date: 2018-09-05 18:40:40.737247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ea1969053c'
down_revision = 'e45d50667cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('loser_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('winner_id', sa.Integer(), nullable=True))
    op.drop_constraint('game_loser_fkey', 'game', type_='foreignkey')
    op.drop_constraint('game_winner_fkey', 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'game_player', ['winner_id'], ['id'])
    op.create_foreign_key(None, 'game', 'game_player', ['loser_id'], ['id'])
    op.drop_column('game', 'winner')
    op.drop_column('game', 'loser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('loser', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('game', sa.Column('winner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key('game_winner_fkey', 'game', 'game_player', ['winner'], ['id'])
    op.create_foreign_key('game_loser_fkey', 'game', 'game_player', ['loser'], ['id'])
    op.drop_column('game', 'winner_id')
    op.drop_column('game', 'loser_id')
    # ### end Alembic commands ###
