"""empty message

Revision ID: 835745a71d15
Revises: 
Create Date: 2018-09-14 17:51:28.285865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '835745a71d15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_date'), 'game', ['date'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=True)
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=True)
    op.create_index(op.f('ix_player_rank'), 'player', ['rank'], unique=False)
    op.create_table('game_player',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('game_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('player_id', sa.String(length=10), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_player_score'), 'game_player', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_player_score'), table_name='game_player')
    op.drop_table('game_player')
    op.drop_index(op.f('ix_player_rank'), table_name='player')
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_game_date'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
