"""empty message

Revision ID: a8db47b5aca6
Revises: 
Create Date: 2018-09-10 23:59:58.455082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8db47b5aca6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_email'), 'player', ['email'], unique=True)
    op.create_index(op.f('ix_player_first_name'), 'player', ['first_name'], unique=True)
    op.create_index(op.f('ix_player_last_name'), 'player', ['last_name'], unique=True)
    op.create_index(op.f('ix_player_rank'), 'player', ['rank'], unique=False)
    op.create_table('game_player',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('player_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_player_score'), 'game_player', ['score'], unique=False)
    op.create_table('game',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('winner_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('loser_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loser_id'], ['game_player.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['game_player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_date'), 'game', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_date'), table_name='game')
    op.drop_table('game')
    op.drop_index(op.f('ix_game_player_score'), table_name='game_player')
    op.drop_table('game_player')
    op.drop_index(op.f('ix_player_rank'), table_name='player')
    op.drop_index(op.f('ix_player_last_name'), table_name='player')
    op.drop_index(op.f('ix_player_first_name'), table_name='player')
    op.drop_index(op.f('ix_player_email'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
