"""empty message

Revision ID: c0c221116043
Revises: f5e4ff8e8b41
Create Date: 2018-09-14 19:33:31.681260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c221116043'
down_revision = 'f5e4ff8e8b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('image_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'image_url')
    # ### end Alembic commands ###
