"""empty message

Revision ID: ffe77dbaeade
Revises: 32ea1969053c
Create Date: 2018-09-05 18:59:03.664820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe77dbaeade'
down_revision = '32ea1969053c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_rank', table_name='player')
    op.create_index(op.f('ix_player_rank'), 'player', ['rank'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_rank'), table_name='player')
    op.create_index('ix_player_rank', 'player', ['rank'], unique=True)
    # ### end Alembic commands ###
